.TH FGL_PRTSCR 3
.SH NAME
fgl_prtscr \- print screen
.SH SYNOPSIS
.B void fgl_prtscr()
.SH DESCRIPTION
.I fgl_prtscr
sends the current screen image to your printer.  The default printer
command is \fBlp -s\fR.  You can change the default by setting the
DBPRINT environment variable.
.SH SUPPORT
Send bug reports to Dave Snyder <dave@snide.com>
